baseURL: "http://projects.chxp.dev/"
languageCode: en-us
title: "chxpdotdev project portfolio"
theme: dead-simple
enableGitInfo: false

menu:
  main:
    - name: "<u>H</u>ome"
      url: /
      weight: 1
      
params:
  author:
    name: chxp

  description: "chxpdotdev's project portfolio site"
  noSearch: true

markup:
  highlight:
    codeFences: true
    style: evergarden
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    goldmark:
      extensions:
        passthrough:
          delimiters:
            block:
            - - \[
              - \]
            - - $$
              - $$
            inline:
            - - \(
              - \)
          enable: true
      renderer:
        unsafe: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

services:
  rss:
    limit: -1